name: Release Workflow

on:
  push:
    tags:
      - "v*.*.*"
env:
  HTTP_PROXY: http://proxycz.oskarmobil.cz:3128
  HTTPS_PROXY: http://proxycz.oskarmobil.cz:3128
  NO_PROXY: localhost,127.0.0.1
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare release branch
        id: maven-release
        uses: stezsky/shared-actions/actions/maven-release@main
